import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:plants_app_using_new_widgets/bottom_screens/cart_screen.dart';
import 'package:plants_app_using_new_widgets/model/plants_model.dart';
import 'package:plants_app_using_new_widgets/provider/cart_items.dart';
import 'package:provider/provider.dart';

void main() {
  testWidgets('to test cart screen to find app bar row', (widgetTester) async {
    var cartScreen = const CartScreen(cartItems: []);

    await widgetTester.pumpWidget(ChangeNotifierProvider(
        create: (_) => CartProvider(), child: MaterialApp(home: cartScreen)));

    expect(find.text('cartTitle'), findsOneWidget);

    var arrowIcon = find.byIcon(Icons.arrow_back);
    expect(arrowIcon, findsOneWidget);
    await widgetTester.tap(arrowIcon);
    await widgetTester.pumpAndSettle();
  });


  // testWidgets('to test cart screen to find row', (widgetTester) async {
  //   var cartScreen = CartScreen(cartItems: [
  //     Plants(title: 'plants1', prize: "\$5.99", Image: 'assets/image_plant1.jpg'),
  //     Plants(title: 'tree', prize: "\$6.90", Image: 'assets/image_plant3.jpg'),
  //   ]);
  //
  //   await widgetTester.pumpWidget(
  //     ChangeNotifierProvider(
  //       create: (_) => CartProvider(),
  //       child: MaterialApp(home: cartScreen),
  //     ),
  //   );
  //
  //   // Find the app bar title
  //   expect(find.text('cartTitle'), findsOneWidget);
  //
  //   // Find the ListView with a specific key
  //   var listviewKey = find.byKey(const Key('listview_key'));
  //   expect(listviewKey, findsOneWidget);
  //
  //   // Verify the presence of individual items in the ListView
  //
  //   var key = find.byKey(const Key('key'));
  //   expect(key, findsOneWidget);
  //
  // });

    testWidgets('Test CartScreen widget', (WidgetTester tester) async {
      // Build our app and trigger a frame.
      await tester.pumpWidget(
        ChangeNotifierProvider(
          create: (_) => CartProvider(),
          child: MaterialApp(
            home: CartScreen(
              cartItems: [
                Plants(
                  title: 'plants1',
                  prize: "\$5.99",
                  Image: 'assets/image_plant1.jpg',
                ),
                Plants(
                  title: 'tree',
                  prize: "\$6.90",
                  Image: 'assets/image_plant3.jpg',
                ),
              ],
            ),
          ),
        ),
      );

      // Verify the presence of individual items in the ListView
      expect(find.descendant(
        of: find.byKey(const Key('listview_key')),
        matching: find.text('plants1'),
      ), findsOneWidget);

      expect(find.descendant(
        of: find.byKey(const Key('listview_key')),
        matching: find.text('tree'),
      ), findsOneWidget);

      // Verify the presence of separators
      expect(find.byKey(const Key('key')), findsNWidgets(1));

      // You can add more specific tests for the separator if needed
      // For example, if you want to check the presence of a Divider widget
      expect(find.byType(Divider), findsNWidgets(1));

      // You can also test the presence of ListTile widgets generated by itemBuilder
      expect(find.byType(ListTile), findsNWidgets(2));// Assuming 2 items in the list
    });
  }


